const InternalEvent = {
  WEB_CONTENT_READY: 'WEB_CONTENT_READY',
  LOCAL_FOLDER_CHANGED: 'LOCAL_FOLDER_CHANGED',
  CLOUD_FOLDER_CHANGED: 'CLOUD_FOLDER_CHANGED',
  UPLOAD_FILE: 'UPLOAD_FILE',
  DELETE_FILE: 'DELETE_FILE',
  OPEN_FILE: 'OPEN_FILE',
  DOWNLOAD_FILE: 'DOWNLOAD_FILE',
  DROP_FILE: 'DROP_FILE',
};

export default InternalEvent;
