const UiEvent = {
  CLIENT: {
    CONNECT: 'UI_SERVER_EVENT.CLIENT.CONNECT',
    DISCONNECT: 'UI_SERVER_EVENT.CLIENT.DISCONNECT',
  },
  SERVER: {
    GIVE_FILE_DIR: 'UI_SERVER_EVENT.SERVER.GIVE_FILE_DIR',
    FILE_UPLOADED: 'UI_SERVER_EVENT.SERVER.FILE_UPLOADED',
  },
};

export default UiEvent;
