const UiEvent = {
  CLIENT: {
    CONNECT: 'UI_EVENT.CLIENT.CONNECT',
    DISCONNECT: 'UI_EVENT.CLIENT.DISCONNECT',
    UPLOAD_FILE: 'UI_EVENT.CLIENT.UPLOAD_FILE',
    DELETE_FILE: 'UI_EVENT.CLIENT.DELETE_FILE',
    DOWNLOAD_FILE: 'UI_EVENT.CLIENT.DOWNLOAD_FILE',
    DROP_FILE: 'UI_EVENT.CLIENT.DROP_FILE',
  },
  SERVER: {
    GIVE_FILE_DIR: 'UI_EVENT.SERVER.GIVE_FILE_DIR',
    ALL_UPLOADED_FILES: 'UI_EVENT.SERVER.ALL_UPLOADED_FILES',
    FILE_UPLOADED: 'UI_EVENT.SERVER.FILE_UPLOADED',
  },
};

export default UiEvent;
